image: docker

services:
  - docker:dind

variables:
  # GIT_STRATEGY: none

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache git alpine-sdk
  - git clone --single-branch -b "$CI_COMMIT_REF_NAME" https://github.com/EricssonResearch/scott-eu.git
  - cd scott-eu

build_planner_reasoner:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - make build
    - make push
  # only:
  #   - master

deploy_to_swarm:
  stage: deploy
  script:
    - cd deployment
    - echo "$CI_REGISTRY_PASSWORD" | docker -H $SWARM_MANAGER login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker -H $SWARM_MANAGER stack deploy -c docker-compose.yml --with-registry-auth scott
  # only:
  #   - master

deploy_to_swarm_erdc:
  stage: deploy
  script:
    - cd deployment
    - echo "$CI_REGISTRY_PASSWORD" | docker -H $SWARM_MANAGER_ERDC login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker -H $SWARM_MANAGER_ERDC stack deploy -c docker-compose.yml --with-registry-auth scott
  # only:
  #   - master
  tags:
    - erdc
