image: docker

services:
  - docker:dind

variables:
  GIT_STRATEGY: none

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache git
  - git clone https://github.com/EricssonResearch/scott-eu.git
  - cd scott-eu

build_planner_reasoner:
  stage: build
  script:
    - cd planner_reasoner
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --build-arg PUBLIC_PORT=3021 -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
#  only:
#    - master

deploy_to_swarm:
  stage: deploy
  script:
    - cd deployment
    - echo "$CI_REGISTRY_PASSWORD" | docker -H $SWARM_MANAGER login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker -H $SWARM_MANAGER stack deploy -c docker-compose.yml --with-registry-auth planner_reasoner
#  only:
#    - master

deploy_to_swarm_erdc:
  stage: deploy
  script:
    - cd deployment
    - echo "$CI_REGISTRY_PASSWORD" | docker -H $SWARM_MANAGER_ERDC login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker -H $SWARM_MANAGER_ERDC stack deploy -c docker-compose.yml --with-registry-auth planner_reasoner
#  only:
#    - master
  tags:
    - erdc
