version: '2'
services:
  warehouse-fuseki:
    image: stain/jena-fuseki
    ports:
     - "3030:3030"
    volumes_from:
     - warehouse-fuseki-config
  warehouse-fuseki-config:
    build: ./fuseki
  sandbox-whc:
    build: ./webapp-whc
    ports:
     - "8080:8080"
  # sandbox-twin:
  #   build: ./sandbox-twin-webapp
  #   ports:
  #    - "8081:8080"
