# This file was extracted from https://surfertas.github.io/rviz/turtlebot/2017/05/08/turtlepi-spin.html

DWAPlannerROS:

 # Robot Configuration Parameters - Kobuki
 max_vel_x: 0.5  # 0.55
 min_vel_x: 0.0
 
 max_vel_y: 0.0  # diff drive robot
 min_vel_y: 0.0  # diff drive robot
 
 max_trans_vel: 0.25 #0.5  # choose slightly less than the base's capability
 min_trans_vel: 0.1  # this is the min trans velocity when there is negligible rotational velocity
 trans_stopped_vel: 0.1
 
 # Warning!
 #   do not set min_trans_vel to 0.0 otherwise dwa will always think
 #   translational velocities
 #   are non-negligible and small in place rotational velocities will be
 #   created.
 
 max_rot_vel: 1.0  # choose slightly less than the base's capability
 min_rot_vel: 0.4  # this is the min angular velocity when there is negligible translational velocity
 rot_stopped_vel: 0.4
 
 acc_lim_x: 1.0 # maximum is theoretically 2.0.
 acc_lim_theta: 2.0
 acc_lim_y: 0.0  # diff drive robot


# Here begins the old config file version. Remove if above one succeeds
controller_frequency: 10.0
TrajectoryPlannerROS:
# max_vel_x: 1.0
# min_vel_x: 0.1
# max_vel_theta: 0.5
# min_in_place_vel_theta: 0.1
#
## acc_lim_theta: 3.2
## acc_lim_x: 2.5
## acc_lim_y: 2.5
# acc_lim_theta: 10.0
# acc_lim_x: 5.0
# acc_lim_y: 5.0
#
 holonomic_robot: false
##TO DO:holonomic_robot: true? false # Version control problem here
## recovery_behaviour_enabled : false
## clearing_rotation_allowed : false
#
## dwa: false
 xy_goal_tolerance: 0.5
 
