local_costmap:
 global_frame: /turtlebot2i/odom
 robot_base_frame: /turtlebot2i/base_footprint
 update_frequency: 5
 publish_frequency: 10
 static_map: false
 rolling_window: true
 width: 1.5
 height: 1.5
 resolution: 0.01
